version: '3'

services:
  nginx:
    image: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - .env
    expose:
      - 443
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html
  
  mariadb:
    image: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306:
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    expose:
      - 9000:
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/rdragan/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/rdragan/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception