version: '3'

services:
  nginx:
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    # depends_on:
    #   - wordpress
    restart: always
    volumes:
      - ./wordpress/public/html:/var/www
  
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    restart: always

volumes:
  db_volume: 